### ISSUE TITLE
你好，问下关于异步线程的问题。

### ISSUE THREAD

**Issue by wy19901227** [johnil/VVeboTableViewDemo#3]
使用了您的vvebo觉得真的特流畅，这才是iphone，其他的app真用处了安卓的感觉。。然后，看了您的代码，大致了解了原理，但是我也按照异步的原理，用的依然是原始的tableview的用法，不过，把cell赋值model的操作用了异步来完成，但是，结果缺不行，我的数据是加载完成的，但是，数据却并不能想你的一样马上显示出来，不知道为什么，您可以帮我解释下嘛》？

部分 代码
- (void)setModel:(BuildModel *)model{
  
  _model = model;
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
  CGFloat width;
  [_houseImgView setBackgroundColor:[UIColor backgroundColor]];
  [_houseImgView sd_setImageWithURL:kURLFromString(_model.path) placeholderImage:_houseImgView.image completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
      if (image.size.width) {

**Comment by wy19901227** [comment]
这些异步线程会按照顺序执行吗？ 是我应该弄个异步线程池吗？让他们按顺序执行？

**Comment by johnil** [comment]
UI的更新要在主线程中执行。
